// lib/data.ts
export const serviceCategories = [
  {
    id: 1,
    name: 'Electrical',
    slug: 'electrical',
    icon: '💡',
    description: 'Electrical repair and maintenance services',
    services: [
      {
        id: 1,
        name: 'Ceiling Fan Repair',
        slug: 'ceiling-fan',
        icon: '🌀',
        description: 'Expert ceiling fan repair and maintenance',
        price: '₹499',
        duration: '1-2 hours',
      },
      {
        id: 2,
        name: 'Table Fan Repair',
        slug: 'table-fan',
        icon: '🌀',
        description: 'Professional table fan repair services',
        price: '₹399',
        duration: '1 hour',
      },
      {
        id: 3,
        name: 'Exhaust Fan Repair',
        slug: 'exhaust-fan',
        icon: '🌀',
        description: 'Exhaust fan repair and replacement',
        price: '₹499',
        duration: '1-2 hours',
      },
      {
        id: 4,
        name: 'Mixer Grinder Repair',
        slug: 'mixer-grinder',
        icon: '⚙️',
        description: 'Mixer grinder motor and parts repair',
        price: '₹599',
        duration: '1-2 hours',
      },
      {
        id: 5,
        name: 'Induction Stove Repair',
        slug: 'induction-stove',
        icon: '🍳',
        description: 'Induction stove repair and servicing',
        price: '₹499',
        duration: '1 hour',
      },
      {
        id: 6,
        name: 'Geyser Repair',
        slug: 'geyser',
        icon: '🛁',
        description: 'Water heater/geyser repair services',
        price: '₹699',
        duration: '2-3 hours',
      },
      {
        id: 7,
        name: 'Water Pump Repair',
        slug: 'water-pump',
        icon: '💧',
        description: 'Water pump repair and maintenance',
        price: '₹799',
        duration: '2-3 hours',
      },
    ],
  },
  {
    id: 2,
    name: 'Home Appliances',
    slug: 'home-appliances',
    icon: '🏠',
    description: 'Home appliance repair services',
    services: [
      {
        id: 8,
        name: 'Refrigerator Repair',
        slug: 'refrigerator',
        icon: '🧊',
        description: 'Refrigerator cooling and parts repair',
        price: '₹899',
        duration: '2-3 hours',
      },
      {
        id: 9,
        name: 'Washing Machine Repair',
        slug: 'washing-machine',
        icon: '👕',
        description: 'Washing machine repair and servicing',
        price: '₹799',
        duration: '2-3 hours',
      },
      {
        id: 10,
        name: 'Microwave Repair',
        slug: 'microwave',
        icon: '🔥',
        description: 'Microwave oven repair services',
        price: '₹599',
        duration: '1-2 hours',
      },
      {
        id: 11,
        name: 'AC Repair',
        slug: 'ac',
        icon: '❄️',
        description: 'AC repair, gas filling, and servicing',
        price: '₹999',
        duration: '2-3 hours',
      },
      {
        id: 12,
        name: 'Chimney Repair',
        slug: 'chimney',
        icon: '🍳',
        description: 'Kitchen chimney repair and cleaning',
        price: '₹699',
        duration: '1-2 hours',
      },
      {
        id: 13,
        name: 'Dishwasher Repair',
        slug: 'dishwasher',
        icon: '🍽️',
        description: 'Dishwasher repair and maintenance',
        price: '₹799',
        duration: '2 hours',
      },
    ],
  },
  {
    id: 3,
    name: 'Electronics',
    slug: 'electronics',
    icon: '📺',
    description: 'Electronic device repair services',
    services: [
      {
        id: 14,
        name: 'LED TV Repair',
        slug: 'led-tv',
        icon: '📺',
        description: 'LED/LCD TV repair and panel replacement',
        price: '₹999',
        duration: '2-3 hours',
      },
      {
        id: 15,
        name: 'Laptop Repair',
        slug: 'laptop',
        icon: '💻',
        description: 'Laptop repair, screen replacement, servicing',
        price: '₹799',
        duration: '1-2 hours',
      },
      {
        id: 16,
        name: 'CCTV Repair',
        slug: 'cctv',
        icon: '📹',
        description: 'CCTV camera repair and installation',
        price: '₹699',
        duration: '2 hours',
      },
      {
        id: 17,
        name: 'Printer Repair',
        slug: 'printer',
        icon: '🖨️',
        description: 'Printer repair and cartridge replacement',
        price: '₹599',
        duration: '1-2 hours',
      },
      {
        id: 18,
        name: 'UPS/Inverter Repair',
        slug: 'ups-inverter',
        icon: '🔋',
        description: 'UPS and inverter repair services',
        price: '₹699',
        duration: '2 hours',
      },
      {
        id: 19,
        name: 'Router Repair',
        slug: 'router',
        icon: '📶',
        description: 'WiFi router repair and configuration',
        price: '₹499',
        duration: '1 hour',
      },
    ],
  },
];

export const blogPosts = [
  {
    id: 1,
    title: '5 Signs Your AC Needs Servicing',
    slug: 'ac-servicing-signs',
    excerpt: 'Learn the warning signs that indicate your air conditioner needs professional servicing.',
    date: 'Jan 15, 2024',
    category: 'Maintenance Tips',
    image: '❄️',
    readTime: '3 min read',
  },
  {
    id: 2,
    title: 'How to Extend Your Refrigerator Life',
    slug: 'refrigerator-life-tips',
    excerpt: 'Simple maintenance tips to keep your refrigerator running efficiently for years.',
    date: 'Jan 10, 2024',
    category: 'Maintenance Tips',
    image: '🧊',
    readTime: '4 min read',
  },
  {
    id: 3,
    title: 'Understanding Warranty and AMC',
    slug: 'warranty-amc-guide',
    excerpt: 'Everything you need to know about warranties and annual maintenance contracts.',
    date: 'Jan 5, 2024',
    category: 'Guides',
    image: '📋',
    readTime: '5 min read',
  },
];